version: 1.0.{build}
init:
- cmd: set path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;%path%
build:
  verbosity: minimal

test_script:
- ps: >-
   
    mstest /testcontainer:UnitTestsAppveyorTests\bin\Debug\UnitTestsAppveyorTests.dll /resultsfile:testResult1.xml
    
    mstest /testcontainer:"UnitTestsAppveyor\UnitTestProject2\bin\Debug\UnitTestProject2.dll /resultsfile:testResult2.xml
    
    Get-ChildItem -Recurse -Filter *.xml
    
    Get-ChildItem -Recurse -Filter *.xml | ForEach-Object {$wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\UnitTestsAppveyorTests\bin\Debug\$_))}  

  
  

#test_script:
#- ps: >-
#    $ErrorActionPreference = "Stop"
    
#    cd UnitTestsAppveyorTests\bin\Debug

#    mstest /testcontainer:UnitTestsAppveyorTests.dll /resultsfile:testResult1.xml
    
#    $?

#    $wc = New-Object 'System.Net.WebClient'
    
#    $?

#    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testResult1.xml))
    
#    $?

#- ps: cd UnitTestsAppveyorTests\bin\Debug
#- ps: mstest /testcontainer:UnitTestsAppveyorTests.dll /resultsfile:testResult1.xml
#- ps: $wc = New-Object 'System.Net.WebClient'
#- ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testResult1.xml))
